<?php

$title = 'Suppliers';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('supplier', array(
        'action'=>'add'));?>">Add new</a></p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Company</th>
    <th>Type</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($suppliers as $supplier) : ?>
<tr>
    <td><?php echo $this->escapeHtml($supplier->name);?></td>
    <td><?php echo $this->escapeHtml($supplier->company);?></td>
    <td><?php echo $this->escapeHtml($supplier->type);?></td>
    <td>
        <a href="<?php echo $this->url("supplier",
                array('action'=>'edit', 'id' => $supplier->idsupplier));?>">Edit</a>
        <a href="<?php echo $this->url('supplier',
            array('action'=>'delete', 'id' => $supplier->idsupplier));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>