<?php

$title = 'Add new';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('material', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idmaterial'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('company'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();